name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - 'main'

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        image: 
          - "swift:6.1.0"
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v2
        with:
          clean: true
          submodules: recursive
      - name: Build
        run: |
          rm -fr .build | echo "Removed build folder"
          swift build -c release --target RHVoiceSwift
